# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Marixza Torres | PhD Candidate"
title_separator          : "-"
name                     : &name "Marixza Torres"
description              : &description "Ph.D. Candidate | Researcher | Educator | Prosocial Development & Cultural Identity"
url                      : "https://MarixzaT.github.io" # Your GitHub Pages URL
baseurl                  : "" # Keep this empty unless using a subdirectory
repository               : "MarixzaT/MarixzaT.github.io" # Your actual GitHub repository name

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"  # Make sure to upload your profile picture to your repository
  name             : "Marixza Torres"
  pronouns         : "she/her"  
  bio              : "Ph.D. Candidate | Researcher | Educator | Prosocial Development & Cultural Identity"
  location         : "University of California, Irvine"
  uri              : "https://MarixzaT.github.io" # Your website link
  email            : "Marixzat@uci.edu"


  # Academic websites
  googlescholar    : https://scholar.google.com/citations?user=CFRJgIwAAAAJ&hl=en
  orcid            : https://orcid.org/0009-0007-9442-4144



  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "academicpages"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

 # Publication Category - The following list categorizes publications
publication_category:
  books:
    title: 'Book Chapters'
  manuscripts:
    title: 'Peer-Reviewed Research Manuscripts'
  conferences:
    title: 'Conference Papers'
  in_progress:
    title: 'Manuscripts in Progress'

    ---
layout: archive
title: "Publications"
permalink: /publications/
author_profile: true
---

## **Peer-Reviewed Research Manuscripts**
- **Torres, M., Carlo, G., & Davis, A. N.** (2025). The associations between culture-related stressors and prosocial behaviors in U.S. Latino/a college students: The mediating role of cultural identity. *Adolescents, 5*(1), 4. [https://doi.org/10.3390/adolescents5010004](https://doi.org/10.3390/adolescents5010004)
- **Partovi, R., Carlo, G., Torres, M., & Cruz, A. M.** (2024). Typologies of cultural stressors and assets: Exploring differential associations with prosocial behaviors and depressive symptoms among Latino/a young adults. *Cultural Diversity and Ethnic Minority Psychology.* [https://doi.org/10.1037/cdp0000663](https://doi.org/10.1037/cdp0000663)

## **Manuscripts in Progress**
- **Davis, A., Carlo, G., Torres, M., Sanders, H., & Cruz, L.** (Under review). Ethnic group differences in economic stress and out-group prosocial behaviors during the COVID-19 pandemic: A cultural process model.
- **Carlo, G., Carrizales, A., Torres, M., Taylor, Z. E., & Ruiz, Y.** (In progress). Family ethnic socialization practices associated with cultural assets, civic responsibility, and prosocial behaviors in rural U.S. Latino/a youth.

## **Book Chapters**
- **Torres, M., Carlo, G., Carpenter, L., & Tran, K.** (Accepted pending revision). Fostering social justice and equity in U.S. ethnic/racial minoritized populations through prosocial behaviors. In D. Lapsley & J. Gibbs (Eds.), *Research Handbook on Lifespan Moral Development.* Edward Elgar Publishing.
- **Carlo, G., Torres, M., Partovi, R., & Cruz, A.** (2024). Moral development. In W. Troop-Gordon & E. Neblett (Eds.), *Encyclopedia of Adolescence (2nd ed.).* New York: Elsevier Press.


# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # change to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :



# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  presentations:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _presentations
  - scope:
      path: ""
      type: presentations
    values:
      layout: presentations
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
